---
# tasks file for fortigate_create_address_object

- name: Create address object
  fortinet.fortios.fortios_firewall_address:
    access_token: "{{ API_KEY }}"
    vdom: "{{ vdom }}"
    firewall_address:
      comment: "Test via Ansible"
      name: "{{ item.name }}"
      obj_id: "ip"
      subnet: "{{ item.host.value | ansible.netcommon.ipaddr('address') }} {{ item.host.value | ansible.netcommon.ipaddr('netmask') }}"
    state: "present"
  loop: "{{ address_objects | list }}"
  when: item.name in objects_to_create
