---
# tasks file for aruba_cx_banner
- name: TASK I - Create Banner
  arubanetworks.aoscx.aoscx_banner:
    state: create
    banner_type: banner
    banner: |
          ------------------------------------------------------------------------------------------------------------------------
               ___      .______       __    __  .______        ___           ______ ___   ___     __          ___      .______
              /   \     |   _  \     |  |  |  | |   _  \      /   \         /      |\  \ /  /    |  |        /   \     |   _  \
             /  ^  \    |  |_)  |    |  |  |  | |  |_)  |    /  ^  \       |  ,----' \  V  /     |  |       /  ^  \    |  |_)  |
            /  /_\  \   |      /     |  |  |  | |   _  <    /  /_\  \      |  |       >   <      |  |      /  /_\  \   |   _  <
           /  _____  \  |  |\  \----.|  `--'  | |  |_)  |  /  _____  \     |  `----. /  .  \     |  `----./  _____  \  |  |_)  |
          /__/     \__\ | _| `._____| \______/  |______/  /__/     \__\     \______|/__/ \__\    |_______/__/     \__\ |______/
          ------------------------------------------------------------------------------------------------------------------------

- name: TASK II - Create Exec Banner
  arubanetworks.aoscx.aoscx_banner:
    state: create
    banner_type: banner_exec
    banner: Welcome!
