FROM ubuntu:18.04

# install packages
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8

RUN apt-get update; \
    apt install -y openssh-client; \
    apt install -y python3-pip; \
    apt install -y git; \
    apt-get clean

RUN pip3 install --upgrade pip; \
    python3 -m pip install ansible; \
    python3 -m pip install paramiko

# install ansible-galaxy collections
RUN ansible-galaxy collection install cisco.nxos
RUN ansible-galaxy collection install cisco.ios
RUN ansible-galaxy collection install arubanetworks.aoscx

# environment variables
ENV ANSIBLE_HOST_KEY_CHECKING=false