FROM jenkins/jenkins:lts

USER root

# Install Docker dependencies
RUN apt-get update && apt-get install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg-agent \
    software-properties-common

# Add Docker's official GPG key
RUN curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -

# Add Docker repository
RUN add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"

# Install Docker using the official script
RUN curl -fsSL https://get.docker.com -o get-docker.sh \
    && sh get-docker.sh

# Add Jenkins user to the docker group
RUN usermod -aG docker jenkins
