---
API_KEY: "H5c6d6bg3tNk4rj5zQsrg74xH355sg"
####################################################
#################### INTERFACES ####################
####################################################
interfaces:
  aggregate:
    name: AGGR_01
    allow_access:
      - ssh
      - ping
      - http
    role: "lan"
    comments: "Made with Ansible"
  vlans:
    - name: VLAN_100
      alias: DATA
      vlan_id: 100
      ip_address: 10.1.100.254/24
      vlan_protocol: 8021q
      aggregate_interface: "AGGR_01"
    - name: VLAN_110
      alias: VOIP
      vlan_id: 110
      ip_address: 10.1.110.254/24
      vlan_protocol: 8021q
      aggregate_interface: "AGGR_01"
    - name: VLAN_120
      alias: MANAGEMENT
      vlan_id: 120
      ip_address: 10.1.120.254/24
      vlan_protocol: 8021q
      aggregate_interface: "AGGR_01"
    - name: VLAN_130
      alias: PRINTERS
      vlan_id: 130
      ip_address: 10.1.130.254/24
      vlan_protocol: 8021q
      aggregate_interface: "AGGR_01"

#########################################################
#################### ADDRESS OBJECTS ####################
#########################################################
address_objects:
  - object_name: object_01
    ip_address: 10.1.1.0
    netmask: 255.255.255.0
  - object_name: object_02
    ip_address: 10.1.2.0
    netmask: 255.255.255.0
  - object_name: object_03
    ip_address: 10.1.3.0
    netmask: 255.255.255.0
  - object_name: object_04
    ip_address: 10.1.4.0
    netmask: 255.255.255.0
  - object_name: object_05
    ip_address: 10.1.5.0
    netmask: 255.255.255.0
  - object_name: object_06
    ip_address: 10.1.6.0
    netmask: 255.255.255.0

###############################################################
#################### ADDRESS GROUP OBJECTS ####################
###############################################################
address_group_objects:
  - group_name: group_01
    members: 
    - name: object_01
    - name: object_02
  - group_name: group_02
    members: 
    - name: object_03
    - name: object_04
  - group_name: group_03
    members: 
    - name: object_05
    - name: object_06

#########################################################
#################### SERVICE OBJECTS ####################
#########################################################
service_objects:
  - name: TCP_8080
    protocol: "TCP/UDP/SCTP"
    tcp_range: "8080-8080"
    comment: "Added with Ansible TCP port 8080"
  - name: TCP_4000-4080
    protocol: "TCP/UDP/SCTP"
    tcp_range: "4000-4080"
    comment: "Added with Ansible TCP port 4000-4080"

###############################################################
#################### SERVICE GROUP OBJECTS ####################
###############################################################

service_group_objects:
  - group_name: WEB_TRAFFIC
    members:
    - name: HTTP
    - name: HTTPS
    comment: "Service group made with Ansible"

##################################################
#################### Policies ####################
##################################################
firewall_policies:
  - policy_name: policy_01
    policy_id: 1
    action: "accept"
    srcintf:
      - name: VLAN_100
    src_address:
      - name: object_01
      - name: object_06
    dstintf:
      - name: VLAN_120
    dst_address:
      - name: group_03
    service:
      - name: ALL
    nat: enable
    status: enable
    comment: "Made with Ansible"
  - policy_name: policy_02
    policy_id: 2
    action: "accept"
    srcintf: 
      - name: VLAN_100
    src_address:
      - name: object_01
    dstintf:
      - name: VLAN_120
    dst_address:
      - name: object_02
    service:
      - name: TCP_8080
    nat: disable
    status: enable
    comment: "Made with Ansible"


################################################
#################### ROUTES ####################
################################################
routes:
  static:
    - sequence: 1
      dst: 0.0.0.0/0
      device: "port1"
      gateway: "10.123.10.254"
      status: "enable"
      comment: "default route"
    - sequence: 2
      dst: 100.65.2.0/25
      device: "VLAN_100"
      gateway: "100.65.1.254"
      status: "enable"
      comment: "Made with Ansible"



